apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-coffee-ingress
  namespace: e-coffee-node
  labels:
    app.kubernetes.io/name: e-coffee-node
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - e-coffee.node
      secretName: e-coffee-tls
  rules:
    - host: e-coffee.node
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: e-coffee-service
                port:
                  number: 80
