apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zanzibar-ingress
  namespace: zanzibar-lounge
  labels:
    app.kubernetes.io/name: zanzibar-lounge
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zanzibar.lounge
      secretName: zanzibar-tls
  rules:
    - host: zanzibar.lounge
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zanzibar-service
                port:
                  number: 80
